"""
CMT Veda AI -- Discovery Engine API (spec #36).

Run locally with:  uvicorn app.main:app --reload
Or via Docker:      docker compose up

The Lovable frontend (built separately) consumes this API. See README.md
for the full endpoint list and docs/openapi.json (auto-generated by
FastAPI at /docs and /openapi.json) for the live contract.
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.api.routers import (
    analysis,
    audit,
    candidates,
    editorial,
    health,
    manual,
    newsletter,
    overview,
    rag,
    runs,
    sources,
)
from app.config import get_settings
from app.database import session_scope
from app.logging_config import configure_logging, get_logger
from app.services.taxonomy_service import seed_default_taxonomy

settings = get_settings()
configure_logging()
logger = get_logger(component="main")

app = FastAPI(
    title="CMT Veda AI - Discovery Engine",
    description=(
        "Backend Discovery Engine: source collection, normalization, deduplication, "
        "Veda Intelligence classification, editorial generation, and the human-controlled "
        "newsletter and RAG workflows. Frontend is built separately in Lovable."
    ),
    version="1.0.0",
)

# All versioned resource routers are aggregated under one APIRouter and
# mounted at settings.api_prefix (default /api/v1) so the whole surface
# shares one FastAPI app instance -- and therefore one set of exception
# handlers, one OpenAPI schema, one /docs page (spec #55: stable,
# documented request/response schemas for the future Lovable frontend).
api_router = APIRouter(prefix=settings.api_prefix)
for router in (sources, runs, candidates, analysis, editorial, newsletter, rag, manual, audit, overview):
    api_router.include_router(router.router)

app.include_router(api_router)
app.include_router(health.router)  # /health, /readiness at root (unversioned, spec #43)


@app.on_event("startup")
def _seed_taxonomy_on_startup() -> None:
    """
    CMT-specific overhaul, Phase 1: `seed_default_taxonomy` was already
    idempotent and documented as "safe to call on every app/worker
    startup," but nothing actually called it outside tests -- that is the
    confirmed root cause of discovery_taxonomy being empty in production
    (see IMPLEMENTATION_STATUS.md). This closes that gap for the API
    process; app/worker/worker.py's run_forever() does the same for the
    worker process, since either could be the first to start.
    """
    # Defensive: app.database.session_scope()/engine is the module-level
    # production engine, not whatever a test's app_client fixture
    # dependency-overrides get_db() to. In tests that don't also migrate
    # that separate engine, discovery_taxonomy may not exist yet -- this
    # is the ONE expected/benign failure mode (a table that plain doesn't
    # exist because the test never migrated that separate engine at all),
    # so it alone is logged quietly and does not crash startup. Any OTHER
    # failure (the table exists but a query fails, a real DB outage, a
    # permissions problem, etc.) is a genuine production configuration
    # problem per corrective prompt #13 ("do not silently swallow
    # production initialization failures with a generic warning") and is
    # logged at ERROR with the full exception so it cannot be missed in
    # log aggregation/alerting -- while STILL not raising, since a
    # crash-looping API process is worse than a degraded one. The
    # `/readiness` endpoint (app/api/routers/health.py) additionally
    # queries the taxonomy table live on every call, independent of this
    # hook's own success/failure belief, so the condition is visible
    # through a diagnostic endpoint too, not just logs.
    try:
        with session_scope() as db:
            inserted = seed_default_taxonomy(db)
        if inserted:
            logger.info("taxonomy_seeded_on_startup", inserted=inserted)
    except Exception as exc:  # noqa: BLE001 - startup must not crash the app over this
        is_missing_table = "no such table" in str(exc).lower() or "does not exist" in str(exc).lower()
        if is_missing_table:
            logger.warning("taxonomy_seed_on_startup_skipped_missing_table", error=str(exc))
        else:
            logger.error("taxonomy_seed_on_startup_failed", error=str(exc), exc_info=True)


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request, exc: StarletteHTTPException):
    return JSONResponse(status_code=exc.status_code, content={"error": exc.detail, "code": str(exc.status_code)})


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc: RequestValidationError):
    return JSONResponse(status_code=422, content={"error": "validation_error", "detail": exc.errors()})
