"""
CMT Veda AI -- Discovery Engine API (spec #36).

Run locally with:  uvicorn app.main:app --reload
Or via Docker:      docker compose up

The Lovable frontend (built separately) consumes this API. See README.md
for the full endpoint list and docs/openapi.json (auto-generated by
FastAPI at /docs and /openapi.json) for the live contract.
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.api.routers import (
    analysis,
    audit,
    candidates,
    editorial,
    health,
    manual,
    newsletter,
    rag,
    runs,
    sources,
)
from app.config import get_settings
from app.logging_config import configure_logging

settings = get_settings()
configure_logging()

app = FastAPI(
    title="CMT Veda AI - Discovery Engine",
    description=(
        "Backend Discovery Engine: source collection, normalization, deduplication, "
        "Veda Intelligence classification, editorial generation, and the human-controlled "
        "newsletter and RAG workflows. Frontend is built separately in Lovable."
    ),
    version="1.0.0",
)

# All versioned resource routers are aggregated under one APIRouter and
# mounted at settings.api_prefix (default /api/v1) so the whole surface
# shares one FastAPI app instance -- and therefore one set of exception
# handlers, one OpenAPI schema, one /docs page (spec #55: stable,
# documented request/response schemas for the future Lovable frontend).
api_router = APIRouter(prefix=settings.api_prefix)
for router in (sources, runs, candidates, analysis, editorial, newsletter, rag, manual, audit):
    api_router.include_router(router.router)

app.include_router(api_router)
app.include_router(health.router)  # /health, /readiness at root (unversioned, spec #43)


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request, exc: StarletteHTTPException):
    return JSONResponse(status_code=exc.status_code, content={"error": exc.detail, "code": str(exc.status_code)})


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc: RequestValidationError):
    return JSONResponse(status_code=422, content={"error": "validation_error", "detail": exc.errors()})
